## Configuracion de Instancia
server:
  port: 8082

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-inventory-orders

## Configuracion de Spring
spring:
  application:
    name: ms-inventory-orders
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:${PGPORT}/${DATABASE}
    username: ${USER}
    password: ${PASSWORD}


    # url: jdbc:h2:mem:testdb
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

## Configuracion secundaria (custom) http://ms-inventory-products/products
getProduct:
  url: https://back-productoselastic-production.up.railway.app/available